version: '3'
services:
  php81:
    container_name: php
    restart: always
    build:
      context: .
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
      - ${WS_PORT:-81}:${WS_PORT:-81}
    volumes:
      - ./src:/app/src
      - ./index.php:/app/index.php
    env_file:
      - .env
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
