version: '3'
services:
  php81:
    container_name: php
    restart: always
    build:
      context: .
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./src:/app/src
      - ./lib:/app/lib
      - ./index.php:/app/index.php
